name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 17
          distribution: liberica
        
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
